### ISSUE TITLE
Unable to acquire sandy coolant

### ISSUE THREAD

**Issue by DCinAC** [MEEPofFaith/Extra-Sand-For-The-Sandbox-Mod#2]
The game now requires unlocking the material before you can use it in the liquid source, as I don't see there is any other way to make sandy coolant than in liquid source, now I am unable to acquire the coolant as this is not avaliable as I have not unlocked itr

please fix this, thanks.

**Comment by MEEPofFaith** [comment]
I'll work on a Sandy Coolant Mixer at some point. Just not now because I've got virtual school to do.

**Comment by DCinAC** [comment]
I tried to make a mixer. Created a pull request too

**Comment by MEEPofFaith** [comment]
I'll make sprites later, I'm too lazy
