### ISSUE TITLE
Infinity repair point literally does nothing

### ISSUE THREAD

**Issue by Austin5003** [MEEPofFaith/Extra-Sand-For-The-Sandbox-Mod#3]
repairSpeed should be set to a nonzero amount
powerUse can be set to exactly 0

**Comment by MEEPofFaith** [comment]
So I'll set it to1. When it was 30, the beam went on and healed every 30 ticks.

**Comment by MEEPofFaith** [comment]
I hope it works now.

**Comment by MEEPofFaith** [comment]
powerUse 0 still requires it to be connected to power for some reason, but that's something I can't fix.
